<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Support\Str;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $godownCodes = DB::table('godowns')->pluck('code')->toArray();

        $users = [
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Shakawat Hosen',
                'email'              => 'shakawat.hosen@example.com',
                'phone_number'       => '01710000001',
                'address'            => 'Dhaka, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => true,
                'email_verified_at'  => Carbon::now(),
                'password'           => Hash::make('password'),
                'status'             => 'active',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Mehedi Hasan',
                'email'              => 'mehedi.hasan@example.com',
                'phone_number'       => '01710000002',
                'address'            => 'Chattogram, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => true,
                'email_verified_at'  => Carbon::now(),
                'password'           => Hash::make('password'),
                'status'             => 'active',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Nusrat Jahan',
                'email'              => 'nusrat.jahan@example.com',
                'phone_number'       => '01710000003',
                'address'            => 'Rajshahi, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => false,
                'email_verified_at'  => null,
                'password'           => Hash::make('password'),
                'status'             => 'inactive',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Tanvir Ahmed',
                'email'              => 'tanvir.ahmed@example.com',
                'phone_number'       => '01710000004',
                'address'            => 'Sylhet, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => true,
                'email_verified_at'  => Carbon::now(),
                'password'           => Hash::make('password'),
                'status'             => 'active',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Sadia Islam',
                'email'              => 'sadia.islam@example.com',
                'phone_number'       => '01710000005',
                'address'            => 'Khulna, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => true,
                'email_verified_at'  => Carbon::now(),
                'password'           => Hash::make('password'),
                'status'             => 'active',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Rafsan Kabir',
                'email'              => 'rafsan.kabir@example.com',
                'phone_number'       => '01710000006',
                'address'            => 'Barisal, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => false,
                'email_verified_at'  => null,
                'password'           => Hash::make('password'),
                'status'             => 'inactive',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Farzana Akter',
                'email'              => 'farzana.akter@example.com',
                'phone_number'       => '01710000007',
                'address'            => 'Rangpur, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => true,
                'email_verified_at'  => Carbon::now(),
                'password'           => Hash::make('password'),
                'status'             => 'active',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Imran Hossain',
                'email'              => 'imran.hossain@example.com',
                'phone_number'       => '01710000008',
                'address'            => 'Mymensingh, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => true,
                'email_verified_at'  => Carbon::now(),
                'password'           => Hash::make('password'),
                'status'             => 'active',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Mitu Chowdhury',
                'email'              => 'mitu.chowdhury@example.com',
                'phone_number'       => '01710000009',
                'address'            => 'Cumilla, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => false,
                'email_verified_at'  => null,
                'password'           => Hash::make('password'),
                'status'             => 'inactive',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'godown_code'        => $godownCodes[array_rand($godownCodes)],
                'name'               => 'Ahsan Habib',
                'email'              => 'ahsan.habib@example.com',
                'phone_number'       => '01710000010',
                'address'            => 'Gazipur, Bangladesh',
                'verification_token' => Str::random(10),
                'is_verified'        => true,
                'email_verified_at'  => Carbon::now(),
                'password'           => Hash::make('password'),
                'status'             => 'active',
                'remember_token'     => Str::random(10),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
